{% set name = "flake8-variables-names" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_variables_names-{{ version }}.tar.gz
  sha256: 30133e14ee2300e13a60393a00f74d98110c76070ac67d1ab91606f02824a7e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - flake8_variables_names
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/best-doctor/flake8-variables-names
  summary: A flake8 extension that helps to make more readable variables names
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
